"""add utterance audio spans

Revision ID: 62ac05216b0a
Revises: 63d81632375d
Create Date: 2026-08-01 15:46:16.080725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ac05216b0a'
down_revision: Union[str, Sequence[str], None] = '63d81632375d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterances', sa.Column('audio_start_ms', sa.Integer(), nullable=True))
    op.add_column('utterances', sa.Column('audio_end_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utterances', 'audio_end_ms')
    op.drop_column('utterances', 'audio_start_ms')
    # ### end Alembic commands ###
