"""add instance_arn to calls

Revision ID: 63d81632375d
Revises: d32f4d43158a
Create Date: 2026-07-31 16:27:32.502250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d81632375d'
down_revision: Union[str, Sequence[str], None] = 'd32f4d43158a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('instance_arn', sa.Text(), nullable=True))
    op.create_index(op.f('ix_calls_instance_arn'), 'calls', ['instance_arn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_instance_arn'), table_name='calls')
    op.drop_column('calls', 'instance_arn')
    # ### end Alembic commands ###
